# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-08-14 22:37:18
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    Input_DTM_DEM = arcpy.Raster("First_Clip_At")
    Upper_Threshold = 90
    Lower_Threshold = 10

    # Process: Slope (Slope) (sa)
    Slope_Raster = "C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Slope_First_1"
    Slope = Slope_Raster
    Slope_Raster = arcpy.sa.Slope(Input_DTM_DEM, "DEGREE", 1, "PLANAR", "METER", "GPU_THEN_CPU")
    Slope_Raster.save(Slope)


    # Process: Raster Calculator (Raster Calculator) (sa)
    Calculated_Slope_Raster = "C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\RasterC_1"
    Raster_Calculator = Calculated_Slope_Raster
    Calculated_Slope_Raster =  (Slope_Raster <= float(Upper_Threshold)) & (Slope_Raster >= float(Lower_Threshold))
    Calculated_Slope_Raster.save(Raster_Calculator)


    # Process: Reclassify (Reclassify) (sa)
    Reclassified_Raster = "C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Reclass_Rast1"
    Reclassify = Reclassified_Raster
    Reclassified_Raster = arcpy.sa.Reclassify(Calculated_Slope_Raster, "VALUE", "", "DATA")
    Reclassified_Raster.save(Reclassify)


    # Process: Con (Con) (sa)
    Con_Reclass_1 = "C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Con_Reclass_1"
    Con = Con_Reclass_1
    Con_Reclass_1 = arcpy.sa.Con(Reclassified_Raster, Reclassified_Raster, "", "Value = 1")
    Con_Reclass_1.save(Con)


    # Process: Raster to Polygon (Raster to Polygon) (conversion)
    Output_polygon_features = "C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\RasterT_Con_Rec1"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPolygon(in_raster=Con_Reclass_1, out_polygon_features=Output_polygon_features)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb", workspace="C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb"):
        Model()
