# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-08-14 23:01:11
"""
import arcpy
from arcpy.sa import *
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def Model1(Crater_Polygon="Crat_Poly2_Final6", DTM_DEM="First_Clip_At", Depth_Table="C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\ZonalSt_Crat_Po1_ExportTable", Diameter_Table="C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Crat_Poly2_Fin_MinimumBoundi_ExportTable"):  # Model1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("ImageAnalyst")


    # Process: Minimum Bounding Geometry (Minimum Bounding Geometry) (management)
    Crat_Poly2_Fin_MinimumBoundi = "C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Crat_Poly2_Fin_MinimumBoundi"
    arcpy.management.MinimumBoundingGeometry(in_features=Crater_Polygon.__str__().format(**locals(),**globals())if isinstance(Crater_Polygon, str) else Crater_Polygon, out_feature_class=Crat_Poly2_Fin_MinimumBoundi, geometry_type="CIRCLE", mbg_fields_option="MBG_FIELDS")

    # Process: Zonal Statistics as Table (Zonal Statistics as Table) (sa)
    ZonalSt_Crat_Po1 = "C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\ZonalSt_Crat_Po1"
    Output_Join_Layer = ""
    arcpy.sa.ZonalStatisticsAsTable(Crat_Poly2_Fin_MinimumBoundi, "ORIG_FID", DTM_DEM.__str__().format(**locals(),**globals())if isinstance(DTM_DEM, str) else DTM_DEM, ZonalSt_Crat_Po1, "DATA", "MIN_MAX", "CURRENT_SLICE", 90, "AUTO_DETECT", "ARITHMETIC", 360, Output_Join_Layer)
    .save(Zonal_Statistics_as_Table)


    # Process: Export Table (Export Table) (conversion)
    arcpy.conversion.ExportTable(in_table=ZonalSt_Crat_Po1, out_table=Depth_Table.__str__().format(**locals(),**globals())if isinstance(Depth_Table, str) else Depth_Table, field_mapping="ORIG_FID \"ORIG_FID\" true true false 0 Long 0 0,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\ZonalSt_Crat_Po1,ORIG_FID,-1,-1;COUNT \"COUNT\" true true false 0 Double 0 0,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\ZonalSt_Crat_Po1,COUNT,-1,-1;AREA \"AREA\" true true false 0 Double 0 0,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\ZonalSt_Crat_Po1,AREA,-1,-1;MIN \"MIN\" true true false 0 Double 0 0,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\ZonalSt_Crat_Po1,MIN,-1,-1;MAX \"MAX\" true true false 0 Double 0 0,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\ZonalSt_Crat_Po1,MAX,-1,-1")

    # Process: Export Table (2) (Export Table) (conversion)
    arcpy.conversion.ExportTable(in_table=Crat_Poly2_Fin_MinimumBoundi, out_table=Diameter_Table.__str__().format(**locals(),**globals())if isinstance(Diameter_Table, str) else Diameter_Table, field_mapping="Id \"Id\" true false false 10 Long 0 10,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Crat_Poly2_Fin_MinimumBoundi,Id,-1,-1;gridcode \"gridcode\" true false false 10 Long 0 10,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Crat_Poly2_Fin_MinimumBoundi,gridcode,-1,-1;Shape_Leng \"Shape_Leng\" true false false 19 Double 0 0,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Crat_Poly2_Fin_MinimumBoundi,Shape_Leng,-1,-1;Shape_Le_1 \"Shape_Le_1\" true false false 19 Double 0 0,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Crat_Poly2_Fin_MinimumBoundi,Shape_Le_1,-1,-1;Shape_Area \"Shape_Area\" true false false 19 Double 0 0,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Crat_Poly2_Fin_MinimumBoundi,Shape_Area,-1,-1;ORIG_FID \"ORIG_FID\" true true false 0 Long 0 0,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Crat_Poly2_Fin_MinimumBoundi,ORIG_FID,-1,-1;MBG_Diameter \"MBG_Diameter\" true true false 0 Double 3 9,First,#,C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb\\Crat_Poly2_Fin_MinimumBoundi,MBG_Diameter,-1,-1")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb", workspace="C:\\Users\\chris\\OneDrive\\Documents\\ArcGIS\\Projects\\New_Analysis2\\Default.gdb"):
        Model1(*argv[1:])
