# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-08-16 17:01:29
"""
import arcpy
from arcpy.sa import *

def Model1(Crater_Polygon, DTM_DEM, Depth_Table, Diameter_Table):  
    arcpy.env.overwriteOutput = True

    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageExt")
    arcpy.CheckOutExtension("ImageAnalyst")

    arcpy.env.workspace = arcpy.env.scratchWorkspace

    Crat_Poly2_Fin_MinimumBoundi = "MBG_Crater_Poly"
    arcpy.management.MinimumBoundingGeometry(
        in_features=Crater_Polygon, 
        out_feature_class=Crat_Poly2_Fin_MinimumBoundi, 
        geometry_type="CIRCLE", 
        mbg_fields_option="MBG_FIELDS"
    )

    ZonalSt_Crat_Po1 = "Zonal_Stats_Crater"
    arcpy.sa.ZonalStatisticsAsTable(
        in_zone_data=Crat_Poly2_Fin_MinimumBoundi, 
        zone_field="ORIG_FID", 
        in_value_raster=DTM_DEM, 
        out_table=ZonalSt_Crat_Po1, 
        statistics_type="MIN_MAX", 
        ignore_nodata="DATA"
    )

    arcpy.conversion.ExportTable(
        in_table=ZonalSt_Crat_Po1, 
        out_table=Depth_Table
    )

    arcpy.conversion.ExportTable(
        in_table=Crat_Poly2_Fin_MinimumBoundi, 
        out_table=Diameter_Table
    )

if __name__ == '__main__':
    Crater_Polygon = arcpy.GetParameterAsText(0)
    DTM_DEM = arcpy.GetParameterAsText(1)
    Depth_Table = arcpy.GetParameterAsText(2)
    Diameter_Table = arcpy.GetParameterAsText(3)

    Model1(Crater_Polygon, DTM_DEM, Depth_Table, Diameter_Table)
