# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-08-15 14:14:58
"""
import arcpy
from arcpy.sa import *
from sys import argv

def Model2(Crater_Polygon, Slope_Zonal_Stats_xlsx, Basin_Zonal_Stats_xlsx, Data_Raster, Folder, Workspace):  
    # Allow overwriting outputs
    arcpy.env.overwriteOutput = True

    # Set the user's workspace and scratch workspace
    arcpy.env.workspace = Workspace
    arcpy.env.scratchWorkspace = Folder

    # Check out necessary licenses
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("Spatial")
    
    # Process: Minimum Bounding Geometry
    MBG_Output_shp_2_ = f"{Folder}/MBG_Output.shp"
    arcpy.management.MinimumBoundingGeometry(in_features=Crater_Polygon, out_feature_class=MBG_Output_shp_2_, geometry_type="CIRCLE", mbg_fields_option="MBG_FIELDS")

    # Process: Simplify Polygon
    MBG_Simple_Output_shp = f"{Folder}/MBG_Simple_Output.shp"
    arcpy.cartography.SimplifyPolygon(in_features=MBG_Output_shp_2_, out_feature_class=MBG_Simple_Output_shp, algorithm="POINT_REMOVE", tolerance="10 Meters")

    # Process: External Slope Calculator
    arcpy.management.CalculateField(in_table=MBG_Simple_Output_shp, field="Slope", expression="round(!MBG_Diamet! / 2, 3)")

    # Process: Internal Basin Calculator
    arcpy.management.CalculateField(in_table=MBG_Simple_Output_shp, field="Basin", expression="round(!MBG_Diamet! * -0.15, 3)")

    # Process: Slope Buffer
    Crat_Poly2_Fin_Simpli_Buffer2 = f"{Folder}/External_Slope.shp"
    arcpy.analysis.Buffer(in_features=MBG_Simple_Output_shp, out_feature_class=Crat_Poly2_Fin_Simpli_Buffer2, buffer_distance_or_field="Slope", line_side="OUTSIDE_ONLY")

    # Process: Zonal Statistics as Table (Slope)
    Slope_Zonal_Stats = f"{Folder}/Slope_Zonal_Stats"
    arcpy.sa.ZonalStatisticsAsTable(Crat_Poly2_Fin_Simpli_Buffer2, "ORIG_FID", Data_Raster, Slope_Zonal_Stats, "DATA", "MIN_MAX_MEAN")

    # Process: Basin Buffer
    Crat_Poly2_Fin_Simpli_Buffer3 = f"{Folder}/Internal_Basin.shp"
    arcpy.analysis.Buffer(in_features=MBG_Simple_Output_shp, out_feature_class=Crat_Poly2_Fin_Simpli_Buffer3, buffer_distance_or_field="Basin")

    # Process: Zonal Statistics as Table (Basin)
    Basin_Zonal_Stats = f"{Folder}/Basin_Zonal_Stats"
    arcpy.sa.ZonalStatisticsAsTable(Crat_Poly2_Fin_Simpli_Buffer3, "ORIG_FID", Data_Raster, Basin_Zonal_Stats, "DATA", "MIN_MAX_MEAN")

    # Process: Export Zonal Stats to Excel
    arcpy.conversion.TableToExcel(Input_Table=Slope_Zonal_Stats, Output_Excel_File=Slope_Zonal_Stats_xlsx)
    arcpy.conversion.TableToExcel(Input_Table=Basin_Zonal_Stats, Output_Excel_File=Basin_Zonal_Stats_xlsx)

if __name__ == '__main__':
    # Global Environment settings
    Model2(*argv[1:])
